baseurl = "/"
title = "Roy Jonuk's Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Roy Jonuk's Personal & Technical Writing Blog"
    description = "Hello and welcome! My name is Roy and this is my personal blog. I am a rising web and software developer and I wanted to create a space to document my learning, both to cement what I study in my mind, and to help others learn with me!"
    github = "https://github.com/corduroyj"
    twitter = "https://twitter.com/DevCorduroy"
    email = "gabejonuk@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
